### PR TITLE
Added tinyalsa for FM

### PR DESCRIPTION
**Pull request by MardonHH**
tinyalsa build support

Signed-off-by: Pankaj Bharadiya pankaj.bharadiya@ti.com

### CODE REVIEW

**Comment by mikeNG** [comment]
is it used anywhere?

**Comment by pcfighter** [comment]
needed for tools like tinymix

**Comment by MardonHH** [comment]
@mikeNG 
https://github.com/LegacyXperia/android_hardware_ti_wpan/blob/cm-11.0/tools/FM/service/src/jni/Android.mk

LOCAL_C_INCLUDES :=\
$(JNI_H_INCLUDE) \
external/tinyalsa/include/tinyalsa

**Comment by rtammekivi** [comment]
We should only merge this if it indeed is needed for FM playback. Currently audio is not working. I gotta take this up sometime

**Pull request closed without merging**
