### PR TITLE
Enable flag for optimized libhwui

### PR DESCRIPTION
**Pull request by MardonHH**

### CODE REVIEW

**Comment by MardonHH** [comment]
Hmm looks like github added some more changes automatically into my pull request it seems.

I only submitted this commit as pull request: https://github.com/MardonHH/android_device_semc_msm7x30-common/commit/fe7aa4efc57151397c3df0c3f6fc88e4badf97f5

@mikeNG @pcfighter

**Comment by MardonHH** [comment]
Btw looks like this also may fix this bug:
http://forum.xda-developers.com/showpost.php?p=54813671&postcount=529

Didnt have seen such glitches on my todays testbuild on ANZU with this commit.

Edit: today i had such a glitch but only for a millisecond (so its now dissapearing faster and impossible to create a screenshot with this glitch). 
Happened when i had much apps open in background and opened an email.

**Comment by MardonHH** [comment]
BTW maybe we should also set BOARD_EGL_WORKAROUND_BUG_10194508 := true
because i dont see that the adreno blob supports  EGL_KHL_gl_colorspace extension in gl extensions viewer.
I saw it was used on earlier LX builds

Will test it in my next testbuild

**Comment by pteek** [comment]
Branches are merged not commits. So, merge a specific set of commits, create a new branch with those commits and merge that.

**Comment by mikeNG** [comment]
I don't know of any other devices that use the 'optimize' hwui flag. Do you have any actual evidence that it improves anything?

About EGL workaround, tagging @Blefish . I thought kitkat blobs didn't need this?

**Comment by MardonHH** [comment]
Overall system responsiveness is a bit more fluid with the optimized hwui it seems
also libhwui.so size changed (old 217,8k new 305,9k) 
also basemark GUI benchmark is now able to run without crash on ANZU.

**Comment by rtammekivi** [comment]
Seeing this in frameworks/native: https://github.com/CyanogenMod/android_frameworks_native/commit/a2ba428a22125558a129c6ba4001dfc2169de2fe

We don't have any color conversion issues though, do we? From the code I can see it trying to use some other color format than rgba_8888 if this is enabled. I remember some time ago there was a method to increase performance (on Adreno 205) by using some kind of srgb buffers, but I am not sure if this patch enables it.

**Comment by mikeNG** [comment]
I found some color issues when recording the screen with CM screencast. The colors are misaligned

**Comment by MardonHH** [comment]
With or without this changes?
Didnt used screencast yet.

**Comment by mikeNG** [comment]
without

**Comment by MardonHH** [comment]
OK.
Here a build with these commits for ANZU for testing.
https://www.androidfilehost.com/?fid=23622183712460491

**Pull request closed without merging**
